### ISSUE TITLE
Open Interval Support

### ISSUE THREAD

**Issue by lukecampbell** [ooici/coverage-model#162]
Can we add support for open intervals in the time_segment argument, an open interval is indicated by a None?

**Comment by lukecampbell** [comment]
I threw together a quick test that illustrates what I'm referring to better. There's an intermediate problem that I can't set values, I can't tell right now if it's a bug or if I'm using the interface incorrectly.

**Comment by caseybryant** [comment]
Open intervals now supported. KeyError failure has been corrected.

Resolved with commit 4e0853d

**Comment by caseybryant** [comment]
Luke,  I submitted your test cases with the commit to avoid doing a merge.  I modified the tests a little bit because you were duplicating time data points by initializing the coverage with 10 time steps then adding time steps that matched those already in the coverage.  That's a different test than what I think you were trying to test here.

I also added another test case - not specifying a time segment.  This defaults to getting the entire data set and is equivalent to time_segement=(None,None).
